FROM alpine:latest

ARG ANSIBLE_VERSION=${ANSIBLE_VERSION:-2.6.4}

RUN apk --cache-dir /root/.cache update && apk --cache-dir /root/.cache upgrade
RUN apk --cache-dir /root/.cache add python2 libffi libffi-dev musl-dev python2-dev py2-pip \
    openssl-dev gcc make rsync \
    groff git openssh-client zip p7zip xz vim

RUN pip install --upgrade pip \
    && pip install botocore boto3 boto awscli \
    && pip install ansible==${ANSIBLE_VERSION} \
	&& rm -rf /root/.cache
