FROM alpine:latest

RUN apk update \
    && apk upgrade \
    && apk add python2 libffi libffi-dev musl-dev python2-dev py2-pip openssl-dev gcc make rsync \
    groff git openssh-client zip p7zip xz vim

RUN pip install --upgrade pip \
    && pip install botocore boto3 boto awscli \
    && pip install ansible=${ANSIBLE_VERSION:2.6.3} \
	&& rm -rf /root/.cache
